# Generated by src/cpp/qt-svg-composite.cpp; do not edit.
# Rendering implementation: Qt 6.11.1

QT_VERSION = "6.11.1"
BUTTON_NORMAL = "#191919"  # opacity 0.10
BUTTON_FOCUSED = "#333333"  # opacity 0.20
BUTTON_PRESSED = "#404040"  # opacity 0.25
