// Qt has a specific rendering routine that I don't want to recreate
// So I call it directly for precomputational purposes

#include <QColor>
#include <QImage>
#include <QPainter>
#include <QSvgRenderer>
#include <QtGlobal>

#include <array>
#include <iostream>

struct ButtonState {
  const char *pythonName;
  const char *opacity;
};

int main() {
  constexpr std::array states{
      ButtonState{"BUTTON_NORMAL", "0.10"},
      ButtonState{"BUTTON_FOCUSED", "0.20"},
      ButtonState{"BUTTON_PRESSED", "0.25"},
  };

  std::cout << "# Generated by src/cpp/qt-svg-composite.cpp; do not edit.\n"
            << "# Rendering implementation: Qt " << qVersion() << "\n\n"
            << "QT_VERSION = \"" << qVersion() << "\"\n";

  for (const ButtonState &state : states) {
    const QByteArray svg =
        QByteArrayLiteral(
            "<svg xmlns=\"http://www.w3.org/2000/svg\" "
            "width=\"1\" height=\"1\" viewBox=\"0 0 1 1\">"
            "<rect width=\"1\" height=\"1\" fill=\"#ffffff\" opacity=\"") +
        state.opacity + QByteArrayLiteral("\"/></svg>");

    QSvgRenderer renderer(svg);
    QImage image(1, 1, QImage::Format_ARGB32_Premultiplied);
    image.fill(QColorConstants::Black);
    QPainter painter(&image);
    renderer.render(&painter);
    painter.end();
    std::cout << state.pythonName << " = \""
              << image.pixelColor(0, 0).name().toStdString() << "\"  # opacity "
              << state.opacity << "\n";
  }
}
